### ISSUE TITLE
ERROR if cases do not contain all library's variants

### ISSUE THREAD

**Issue by d-t-n** [yammadev/cbrs#1]
Hi,

Thank you for the great implementation regarding CBR.! 
I was testing the code and saw that if the cases list to be tested does not contain all the variants of the original library dataset (removed some options), it is not able to broadcast the new case option and calculate the distances correctly - code below:
"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-50-1542fab7cebc> in <module>
     17 
     18         # Calculate mahalanobis distance between case row and base cases, and store it
---> 19         distances[j] = distance.mahalanobis(case_row, base_row, inverse_covariance_matrix)
     20 
     21     # Returns the index (row) of the minimum value in distances calculated

~\tensorflow\lib\site-packages\scipy\spatial\distance.py in mahalanobis(u, v, VI)
   1074     v = _validate_vector(v)
   1075     VI = np.atleast_2d(VI)
-> 1076     delta = u - v
   1077     m = np.dot(np.dot(delta, VI), delta)
   1078     return np.sqrt(m)

ValueError: operands could not be broadcast together with shapes (11,) (14,) 
"

Have you thought a way to solve that?

Thank you.

**Comment by yammadev** [comment]
Hello @d-t-n thanks for your issue report! -- I believe this error could be related with the minimum distance assigned, or the shape of the space. I'm not sure how's a good way to fix it, if you have any idea, feel free to contribute 👍 Thanks for your time and comments!
